# Generated by Django 5.1.15 on 2026-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the song.", max_length=255
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        help_text="The name of the artist or band.", max_length=255
                    ),
                ),
                (
                    "album",
                    models.CharField(
                        blank=True,
                        help_text="The album this song belongs to (optional).",
                        max_length=255,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="The audio file for the song.",
                        upload_to="songs/audio/",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cover art for the song (optional).",
                        null=True,
                        upload_to="songs/covers/",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration of the song in seconds."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the song was added."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the song was last updated."
                    ),
                ),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
                "ordering": ["-created_at"],
            },
        ),
    ]
