# Generated by Django 5.1.15 on 2026-06-15 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If true, the song is visible in the public feed. If false, only the owner can see it.",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="owner",
            field=models.ForeignKey(
                default=1,
                help_text="The user who uploaded this song.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
