# Generated by Django 5.1.15 on 2026-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_song_is_public_song_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="The audio file for the song.",
                null=True,
                upload_to="songs/audio/",
            ),
        ),
    ]
