# Generated by Django 5.1.15 on 2026-06-17 07:49

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("music", "Profile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


def remove_profiles(apps, schema_editor):
    pass  # cascade handles cleanup


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_profile"),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, remove_profiles),
    ]
