# Generated by Django 5.1.15 on 2026-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_backfill_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
