# Generated by Django 5.1.15 on 2026-06-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
