# Generated by Django 5.1.15 on 2026-06-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_song_duration_song_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="duration",
        ),
        migrations.AlterField(
            model_name="song",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
