# Generated by Django 5.1.15 on 2026-06-25 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_remove_song_duration_alter_song_duration_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["is_public", "-created_at"], name="song_public_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["owner", "-created_at"], name="song_owner_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["owner", "is_public"], name="song_owner_public_idx"
            ),
        ),
    ]
